rm(list=setdiff(ls(),'params'))

if(params$dist.met == 'spearman'){
	# Compute correlation matrix
	mat.cmd <- paste(params$matlab.path,' -nodisplay -r "cd(\'',params$homedir,'code/modmax/\'); homedir = \'',params$homedir,'\'; ',
	                 'opdir = \'',params$opdir,'\'; BCT_path =\'',params$BCT.path,'\'; run(\'computeSubjCorrMat.m\'); exit;"',sep='')
	print('Sending to shell:')
	print(mat.cmd)
	print('....')
	system(mat.cmd)
}

# if using an an alternate distance metric, the file 'subjectCorrMat.mat' will be generated by a separate script using a custom distance metric
# Run Louvain clustering and consensus selection of partition
mat.cmd <- paste(params$matlab.path,' -nodisplay -r "cd(\'',params$homedir,'code/modmax/\'); homedir = \'',params$homedir,'\'; ',
                 'opdir = \'',params$opdir,'\'; BCT_path =\'',params$BCT.path,'\'; nreps = ',params$nreps_gammasweep,'; run(\'npsubjcommPartitionQuality.m\'); exit;"',sep='')
print('Sending to shell:')
print(mat.cmd)
print('....')
system(mat.cmd)