rm(list = setdiff(ls(), c("params","extralab")))
homedir <- params$homedir
setwd(homedir)
savedir <- paste(params$resultsdir,'predictdisease/',sep='')
dir.create(savedir,recursive=T)
source('code/misc/fxns.R')
source('code/misc/trainfxns.R')
source('code/misc/plottingfxns.R')
patientSample <- read.csv(paste(params$opdir,'processed/patientSample.csv',sep=''),stringsAsFactors=F)[,-(1:2)] # Get rid of index column and INDDIDs

##################
### Make plots ###
##################

load(file = paste(savedir,'predictcluster_GLMperf',extralab,'.RData',sep=''))
clusterColors <- getClusterColors(length(cluster.res))

p1 <- plot.featureweights.lm.contintsplit(cluster.res,df,clusterColors)

w.multiplier <- 1
if(grepl('CSFGene',extralab)){w.multiplier <- 2} # make plot wider if both csf and gene betas 
if(grepl('CSFOnly',extralab)){ # for CSF only plots in figure 8, make resized feature weights that fit with performance metrics
  p1 <- p1 + theme(legend.position = 'none',text=element_text(size = 6),plot.title = element_blank()) # remove legend and use one generated by pd_plotperfglm.R
  w.multiplier <- 0.5
}
ggsave(filename = paste(savedir,'GLMClusterFeatureWeights',extralab,'.pdf',sep=''),plot = p1,
       height = 4.8,width=5*w.multiplier,units='cm')

# traditional disease label
load(file = paste(savedir,'predictdz_GLMperf',extralab,'.RData',sep=''))
list[patientSample,dz.short]<- other.dz(patientSample)
if(grepl('CSFOnly',extralab) | grepl('CSFGene',extralab)){
	pal <- colorRampPalette(brewer.pal(name = 'Blues',n=9))
	dz.colors <- pal(9)[3:(3+length(dz.res)-1)] # pick good range of blues
}
if(grepl('GeneOnly',extralab)){
	pal <- colorRampPalette(brewer.pal(name = 'Set3',n=12))
	dz.colors <- pal(length(dz.short)) # assign a color to each disease
	# select only diseases included in analysis
	dz.colors <- dz.colors[dz.short %in% names(dz.res)]
}

p2 <- plot.featureweights.lm.contintsplit(dz.res,df,dz.colors)

w.multiplier <- 1
h.multiplier <- 1
if(grepl('CSFGene',extralab)){w.multiplier <- 2} # make plot wider if both csf and gene betas 
if(grepl('CSFOnly',extralab)){ # for CSF only plots in figure 8, make resized feature weights that fit with performance metrics
  p2 <- p2 + theme(legend.position = 'none',text=element_text(size = 6),plot.title = element_blank()) # remove legend and use one generated by pd_plotperfglm.R
  w.multiplier <- 0.5
  h.multiplier <- 1.2
}
ggsave(filename = paste(savedir,'GLMTraditionalDiseaseFeatureWeights',extralab,'.pdf',sep=''),plot = p2,
       height = 5*h.multiplier,width=5*w.multiplier,units='cm')
